// 한국어 약어 → bible_krv.json 키 매핑
// bible_krv.json은 한국어 약어를 키로 사용 (예: "창", "출", "마", "요")

export const BIBLE_BOOKS: Record<string, { name: string; chapters: number }> = {
  // 구약 (Old Testament)
  '창': { name: '창세기', chapters: 50 },
  '출': { name: '출애굽기', chapters: 40 },
  '레': { name: '레위기', chapters: 27 },
  '민': { name: '민수기', chapters: 36 },
  '신': { name: '신명기', chapters: 34 },
  '수': { name: '여호수아', chapters: 24 },
  '삿': { name: '사사기', chapters: 21 },
  '룻': { name: '룻기', chapters: 4 },
  '삼상': { name: '사무엘상', chapters: 31 },
  '삼하': { name: '사무엘하', chapters: 24 },
  '왕상': { name: '열왕기상', chapters: 22 },
  '왕하': { name: '열왕기하', chapters: 25 },
  '대상': { name: '역대상', chapters: 29 },
  '대하': { name: '역대하', chapters: 36 },
  '스': { name: '에스라', chapters: 10 },
  '느': { name: '느헤미야', chapters: 13 },
  '에': { name: '에스더', chapters: 10 },
  '욥': { name: '욥기', chapters: 42 },
  '시': { name: '시편', chapters: 150 },
  '잠': { name: '잠언', chapters: 31 },
  '전': { name: '전도서', chapters: 12 },
  '아': { name: '아가', chapters: 8 },
  '사': { name: '이사야', chapters: 66 },
  '렘': { name: '예레미야', chapters: 52 },
  '애': { name: '예레미야애가', chapters: 5 },
  '겔': { name: '에스겔', chapters: 48 },
  '단': { name: '다니엘', chapters: 12 },
  '호': { name: '호세아', chapters: 14 },
  '욜': { name: '요엘', chapters: 3 },
  '암': { name: '아모스', chapters: 9 },
  '옵': { name: '오바댜', chapters: 1 },
  '욘': { name: '요나', chapters: 4 },
  '미': { name: '미가', chapters: 7 },
  '나': { name: '나훔', chapters: 3 },
  '합': { name: '하박국', chapters: 3 },
  '습': { name: '스바냐', chapters: 3 },
  '학': { name: '학개', chapters: 2 },
  '슥': { name: '스가랴', chapters: 14 },
  '말': { name: '말라기', chapters: 4 },
  // 신약 (New Testament)
  '마': { name: '마태복음', chapters: 28 },
  '막': { name: '마가복음', chapters: 16 },
  '눅': { name: '누가복음', chapters: 24 },
  '요': { name: '요한복음', chapters: 21 },
  '행': { name: '사도행전', chapters: 28 },
  '롬': { name: '로마서', chapters: 16 },
  '고전': { name: '고린도전서', chapters: 16 },
  '고후': { name: '고린도후서', chapters: 13 },
  '갈': { name: '갈라디아서', chapters: 6 },
  '엡': { name: '에베소서', chapters: 6 },
  '빌': { name: '빌립보서', chapters: 4 },
  '골': { name: '골로새서', chapters: 4 },
  '살전': { name: '데살로니가전서', chapters: 5 },
  '살후': { name: '데살로니가후서', chapters: 3 },
  '딤전': { name: '디모데전서', chapters: 6 },
  '딤후': { name: '디모데후서', chapters: 4 },
  '딛': { name: '디도서', chapters: 3 },
  '몬': { name: '빌레몬서', chapters: 1 },
  '히': { name: '히브리서', chapters: 13 },
  '약': { name: '야고보서', chapters: 5 },
  '벧전': { name: '베드로전서', chapters: 5 },
  '벧후': { name: '베드로후서', chapters: 3 },
  '요일': { name: '요한일서', chapters: 5 },
  '요이': { name: '요한이서', chapters: 1 },
  '요삼': { name: '요한삼서', chapters: 1 },
  '유': { name: '유다서', chapters: 1 },
  '계': { name: '요한계시록', chapters: 22 },
};

// 긴 약어를 먼저 매칭하기 위해 길이순으로 정렬된 키 배열
export const BIBLE_BOOK_KEYS = Object.keys(BIBLE_BOOKS).sort(
  (a, b) => b.length - a.length
);
